# Generated by Django 6.0.5 on 2026-05-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
