# Generated by Django 6.0.5 on 2026-05-15 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_teacher_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classroom'),
        ),
    ]
