# Generated by Django 6.0.5 on 2026-06-06 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_classroom_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'classroom', 'date')},
        ),
    ]
